development:
  adapter: postgresql
  encoding: utf8
  database: accounting_system
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: accounting_system
  username: postgres
  password: postgres
  host: localhost

